### ISSUE TITLE
Upload this to maven central

### ISSUE THREAD

**Issue by lz1998** [thewca/tnoodle-lib#19]

**Comment by suushiemaniac** [comment]
Maven Central is old, requires manual (!) approval by people working at Sonatype and also somewhat obsolete since JCenter was created.

Can you please specify more details why you would like this to be hosted on Maven Central?
If there is a compelling use-case, I may go through the suffering of Maven Central publication.

**Comment by lz1998** [comment]
I hope to use tnoodle as a lib. 
But when I use "mvn package", only those dependencies in pom.xml will be packaged into the jar.

**Comment by suushiemaniac** [comment]
The Maven artifacts produced by this project, especially `org.worldcubeassociation.tnoodle:lib-scrambles` are now hosted at Maven Central.

closed as per #25
